#setwd('~/tmonitor2')
options(stringsAsFactors=FALSE)
today <- as.Date(Sys.time())
todaysfile <- paste0(today, '.csv')
dat <- read.csv(todaysfile)
dat$Time <- as.POSIXct(dat$Time)
plot(dat$Time, dat[,1], type='l', main=today, ylab='Degrees F', xlab=)

png('plot.png', height=400, width=600)
    plot(s1 ~ Time, dat, xaxt = "n", type = "l", main=today)
    title(paste("Last record at:", dat[nrow(dat), 'Time']), line=0.5, cex.main=0.9)
    xax <- pretty(dat$Time)
    axis(1, xax, format(as.POSIXct(xax, origin="1970-01-01"), "%H:%M"), cex.axis = .7, las=2)
dev.off()
